#######################################################
# Verify - on branches
#######################################################


#######################################################
# Package - on merge
#######################################################


#######################################################
# Release - manual deploy
#######################################################
