variables:
  PRIVATE_ECR_IMAGE: 438167243279.dkr.ecr.us-west-2.amazonaws.com/bestbuy:1.0

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:14
  script:
    - echo "Running tests"
    - npm --prefix ./web install ./web
    - npm --prefix ./web install mocha
    - npm --prefix ./web run test

test-runner-pull:
  stage: test
  image: $PRIVATE_ECR_IMAGE
  script:
    - echo "Hello World!"

test-dind-pull:
  stage: test
  image: docker:19.03.15
  services:
    - docker:19.03.15-dind
  script:
    - docker pull $PRIVATE_ECR_IMAGE

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
