---
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - plan

dummy_plan:
  stage: plan
  image:
    name: hashicorp/terraform:1.1.6
    entrypoint: [""]
  script:
    - cd terraform/infrastructure
    - terraform init
    - terraform plan
  rules:
    - if: '$CI_COMMIT_REF_NAME != "master"'
      when: always
    - when: never
  tags:
    - docker
    - dind