# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.latest.gitlab-ci.yml
# https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml

stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:19.03.12
  only:
    - master
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t "$CI_IMAGE" -f ./web/Dockerfile ./web
    - docker build -t "$CI_IMAGE-test" -f ./web/Dockerfile.test ./web
    - docker run --rm "$CI_IMAGE-test"
    - if [ $? -ne 0 ]; then echo "Previous command failed"; fi;
    - docker rmi "$CI_IMAGE-test"
    - docker tag "$CI_IMAGE" "$CI_REGISTRY/$CI_DEPLOY_USER/$CI_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY/$CI_DEPLOY_USER/$CI_IMAGE:$CI_COMMIT_REF_SLUG"
