variables:
  ECR_REPO: bestbuy
  ECR_URI: 438167243279.dkr.ecr.us-west-2.amazonaws.com

.only-default: &only-default
  only:
    - master
    - branches
    - merge_requests
    - tags

stages:
  - test
  - build
  - deploy

mocha-test:
  <<: *only-default
  stage: test
  image: node:14
  script:
    - echo "Running tests"
    - npm --prefix ./web install ./web
    - npm --prefix ./web install mocha
    - npm --prefix ./web run test

docker-build:
  stage: build
  image: docker:19.03.15
  services:
    - docker:19.03.15-dind
  script:
    - docker build -t "$ECR_REPO" -f ./web/Dockerfile ./web
    - docker tag "$ECR_REPO" "$ECR_URI/$ECR_REPO:$CI_COMMIT_REF_SLUG"
    - docker push "$ECR_URI/$ECR_REPO:$CI_COMMIT_REF_SLUG"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy_staging:
  stage: deploy
  image:
    name: bitnami/kubectl:1.18
    entrypoint: [""]
  script:
    - kubectl config view
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
